### ISSUE TITLE
Callback when certs change

### ISSUE THREAD

**Issue by rendaw** [FlorianUekermann/rustls-acme#9]
I have a subprocess that needs to be restarted when the certs change.  I didn't see a way for the user to get notified when they change - would it be difficult to add that as a feature?

**Comment by FlorianUekermann** [comment]
Sorry, I thought I replied to this. The API will change later this year to include a config object and some other general improvements. Progress on this is on hold until then, but I don't see any reason why this shouldn't be supported right now.

Maybe an awaitable notification object (probably a stream) would be more appropriate. Comments on how you would like to use this and why that subprocess needs to be restarted would be great, so I understand the problem properly before I come up with an API.

**Comment by rendaw** [comment]
Oh yeah, sure! In my case specifically I need a cert for a matrix server.  I already have rust doing various other management tasks, so plugging this in to refresh the cert would be more convenient than setting up/debugging an acme-capable reverse proxy.  Restarting the matrix server when the cert gets refreshed isn't an issue, the clients can tolerate some network failures.

**Comment by rendaw** [comment]
FWIW my plan was to write the cert to disk somewhere when it changes and restart the matrix subprocess.

**Comment by joshtriplett** [comment]
I'm interested in this as well, because I'd like to store the certificate and account key somewhere other than on disk. I'd like to use rustls-acme but not have it write to disk itself.

**Comment by FlorianUekermann** [comment]
I started working on v0.3.0. Does this look good?
```
#[async_trait]
pub trait CertifiedKeyCache {
    async fn load(&self, domains: &[String], directory_url: &str) -> Option<CertifiedKey>;
    async fn store(&mut self, domains: &[String], directory_url: &str, cert: &CertifiedKey);
}

#[async_trait]
pub trait AccountKeyCache {
    async fn load(&self, contact: &[String], directory_url: &str) -> Option<EcdsaKeyPair>;
    async fn store(&mut self, contact: &[String], directory_url: &str, account: &EcdsaKeyPair);
}
```

**Comment by joshtriplett** [comment]
That looks great!

**Comment by FlorianUekermann** [comment]
There's one detail that worries me a bit, particularly on the load side of things. The caches could either return `Option<CertifiedKey>` or `Result<Option<CertifiedKey>>`. The difference is that `None` and `Ok(None)` mean slightly different things. `None` would imply that either something went wrong, or no cert was found. `Ok(None)` means nothing went wrong and no cert was found.
I opted for the former above, because the library can't really do anything about it anyway except log the error, which may just as well be done by the cache implementation.
But it could _not_ do something in reaction to an error, like not get a new certificate. This seems stupid, because then the service breaks, which is obviously bad. On the other hand, it may arguably be worse to keep asking the CA for new certs if the cache is broken for whatever reason, because exhausting the rate limit turns a fixable problem into a temporarily unfixable problem.

**Comment by FlorianUekermann** [comment]
> Do those traits only get called for storage when the value changes, or do they get called repeatedly and they have to notice if the value is the same? I'm hoping the former, which would make storage logistics much easier to manage.

Nothing is implemented yet. I planned on triggering store after receiving a new cert from the CA. Load would be triggered on startup I guess, unless we can come up with a reason why attempting to load before a cert refresh makes sense in practice.

**Comment by joshtriplett** [comment]
Also, might it make sense to combine the two caches and just have four methods?

**Comment by FlorianUekermann** [comment]
> Also, might it make sense to combine the two caches and just have four methods?

Yes. Especially because the caches will likely share storage access details (paths, credentials etc), most people will want to implement both in one type to avoid unnecessary duplication. That's more on the config side though, where you want to be able to provide one object that implements both traits, so you don't have to instantiate the shared bits twice. Keeping the traits separate is fine.

The `DirCache` and `NoCache` types I provide will implement both traits.

For anyone who does wants to combine different kinds of cache, wrapping them in a composite one is trivial.

**Comment by FlorianUekermann** [comment]
> Regarding the error type, I do think you can't really do anything _with_ the error other than pass it through. So, I can see a couple of options, with different complexity levels:

Yes exactly. You make an interesting point though with the "pass it through" part. I worked with the assumption that the user will never get the error, which reflects how things work at the moment (`run()` never returns). Maybe that should change. I'll have to see how this plays with the ideas for runtime independence.

> * `Result<Option<CertifiedKey>, E>` where `E` is an associated type for the cache trait, giving flexibility to the trait to use whatever error type it wants. You can then have an AcmeError variant `CacheError` containing a boxed error, and return that. This adds a little bit of complexity, but it's otherwise much easier for prospective users of this interface to deal with, because they can just declare an appropriate error type and then use `?`.

Didn't think about adding an associated type. I'll try that out. `?` also works with boxed errors though, iirc.

**Comment by FlorianUekermann** [comment]
The associated error seems fine so far. A downside is that it carries through to the config object and via that one ends up infecting the rest of the library. Maybe that's ok though, not sure. I was able to avoid that previously by using `Box<dyn ...>` for the cache itself.
```
pub struct ResolvesServerCertUsingAcmeConfig<EC, EA> {
    directory_url: String,
    domains: Vec<String>,
    cache: Box<dyn CertifiedKeyCache<E=EC> + AccountKeyCache<E=EA>>,
}
```
The code above is just an illustration, because if the config is generic anyway `cache` doesn't need to be boxed anymore. But the point is that this would carry through to higher level stuff until some point where I or someone else decides to `Box<dyn ...>` it. I'll stick with this for now and see how I fell about it later when I can take a step back and look at ergonomics of the whole situation (which may also include shortening some type names).

**Comment by joshtriplett** [comment]
I was suggesting boxing it the moment you make it into an AcmeError.

**Comment by FlorianUekermann** [comment]
> I was suggesting boxing it the moment you make it into an AcmeError.

Yes, I got that and I think that is a good idea. It will still make the config and also the resolver generic though (unless I use some boxing tricks around the config in the resolver). My main concern is unnecessarily spilling type arguments into higher level libraries and making those less ergonomic or annoying to implement (or incompatible with caches that choose the "wrong" error type). We'll see how things turn out, there are enough good options on the table.

**Comment by FlorianUekermann** [comment]
`0.3.0-beta.1` is published and solves this issue. Use #18 to the continue discussion.
